services:
  back:
    container_name: Server
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - mysql

  mysql:
    image: mysql
    container_name: Mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysecure
    ports:
      - "3309:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  postgres:
    image: postgres:16.4
    container_name: Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecure
    ports:
      - "3308:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  client:
    container_name: Client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    expose:
      - "8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - back
