version: "2.23"

services:

  back: 
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back/volumes/safebase:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysecure
    ports:
      - "3309:3306"
    volumes:
      - ./back/volumes/mysql:/var/lib/mysql

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verysecure
    ports:
      - "3308:5432"
    volumes:
      - ./back/volumes/postgres:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/volumes/safebase:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - back

